name: Feature Build e Test

on:
  push:
    branches:
      - feature/*

jobs:
  build:
    name: Build e Teste
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build com Maven
        run: mvn -B clean install

      - name: Run testes
        run: mvn test