name: Develop Build and Test

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build e Teste
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build com Maven
        run: mvn -B clean install

      - name: Run testes
        run: mvn test

      - name: Configurando AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Encotrar diretório
        run: ls

      - name: Deploy na AWS
        run: |
          pwd
          whoami
          ls -al
          chmod +x ./deploy.sh
          ./deploy.sh

      - name: Deploy realizado com sucesso
        if: success()
        run: echo 'Deployment successful!'